[package]
name = "learn_pointer"
version = "0.1.0"
authors = ["kentory <1935624920@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
