[package]
name = "tar"
version = "0.1.0"
authors = ["chaos-hj"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = {version = '1.0.20'}
tar = {version = '0.4.33'}